apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-green
  namespace: green
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myapp
      version: green
  template:
    metadata:
      labels:
        app: myapp
        version: green
    spec:
      containers:
      - name: frontend
        image: myrepo/frontend:latest
        ports:
        - containerPort: 3000
      - name: backend
        image: myrepo/backend:latest
        ports:
        - containerPort: 5000
