apiVersion: v1
kind: Service
metadata:
  name: myapp-service-blue
  namespace: blue
spec:
  selector:
    app: myapp
    version: blue
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
