apiVersion: v1
kind: Service
metadata:
  name: myapp-service-green
  namespace: green
spec:
  selector:
    app: myapp
    version: green
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
